-- Insert categories
INSERT INTO Categories (name, description) VALUES
('Local', 'News and information from your local area'),
('Sport', 'Sports news, events, and updates'),
('Lifestyle', 'Fashion, health, travel, and lifestyle content'),
('Entertainment', 'Movies, music, TV shows, and celebrity news'),
('Motoring', 'Cars, motorcycles, and automotive news'),
('Technology', 'Tech news, gadgets, and digital innovations'),
('Business', 'Business news, market analysis, and financial updates'),
('Politics', 'Political news, government policies, and elections'),
('Education', 'Educational news, academic research, and learning resources'),
('Health', 'Health news, medical breakthroughs, and wellness advice'),
('Science', 'Scientific discoveries, research findings, and innovations'),
('Environment', 'Environmental news, climate change, and sustainability'),
('Food', 'Food news, recipes, restaurant reviews, and culinary trends'),
('Real Estate', 'Property news, market trends, and housing advice'),
('Travel', 'Travel destinations, tips, and industry news'),
('Fashion', 'Fashion trends, designer news, and style guides'),
('Art', 'Art exhibitions, artist profiles, and cultural events'),
('Books', 'Book reviews, author interviews, and publishing news'),
('Gaming', 'Video game news, reviews, and industry updates'),
('Fitness', 'Fitness trends, workout advice, and sports science'),
('Finance', 'Personal finance advice, investment strategies, and economic news'),
('Agriculture', 'Farming news, agricultural technology, and food production'),
('Law', 'Legal news, court cases, and legislative updates'),
('Media', 'Media industry news, journalism, and communication trends'),
('Religion', 'Religious news, faith communities, and spiritual topics'),
('Social Issues', 'Social justice, equality, and community initiatives'),
('Transportation', 'Transportation news, infrastructure, and mobility solutions'),
('Energy', 'Energy news, renewable resources, and power generation'),
('Manufacturing', 'Manufacturing news, industry trends, and production methods'),
('Retail', 'Retail news, consumer trends, and shopping advice'); 